### PR TITLE
test

### PR DESCRIPTION
**Pull request by penny777eth**

### CODE REVIEW

**Comment by liyishuai** [comment]
Are you sure you want to merge `Next-DAO:master` into this repository?

**Comment by penny777eth** [comment]
> Are you sure you want to merge `Next-DAO:master` into this repository?

Yep, thanks for mentioning it! I have already written another one to merge. >_<

**Comment by liyishuai** [comment]
请学习GitHub PR的使用方法。

当前拉取请求的含义是：请将[`Next-DAO:master`](https://github.com/Next-DAO/chinese-copywriting-guidelines/tree/master)中的全部变更同步到[`sparanoid:master`](https://github.com/sparanoid/chinese-copywriting-guidelines/tree/master)，包括：
- [删除`CHANGELOG.md`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)
- [删除`README.en.md`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-b4f47ddd2e9baf4f63a8b1c7adb79cc6caabfe2958e82d73d7b80d1468075213)
- [在`README.md`中执行354行变更](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
- [删除`README.zh-Hans.md`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-ac136fd5500e4bed851634e02236c48d5d66c90e625abb8e0709bde4d183ad83)
- [删除`crowdin.yml`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-256aa18d225b85dd7da40aba5091225c2b6c93e8e40f8955fc92be6c5a674afc)
- [删除`package.json`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
- [删除`pnpm-lock.yaml`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb)
- [删除`renovate.json`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57)

上述变更，以我的理解，是 **将[本仓库](https://github.com/sparanoid/chinese-copywriting-guidelines)适配到[Next-DAO团队](https://github.com/Next-DAO)** 的行为。应只存在于[Next-DAO分叉](https://github.com/Next-DAO/chinese-copywriting-guidelines)下，而非提交至本仓库。

行动建议：关闭此拉取请求（Close pull request）。

**Comment by penny777eth** [comment]
> 请学习GitHub PR的使用方法。
> 
> 当前拉取请求的含义是：请将[`Next-DAO:master`](https://github.com/Next-DAO/chinese-copywriting-guidelines/tree/master)中的全部变更同步到[`sparanoid:master`](https://github.com/sparanoid/chinese-copywriting-guidelines/tree/master)，包括：
> 
> * [删除`CHANGELOG.md`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)
> * [删除`README.en.md`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-b4f47ddd2e9baf4f63a8b1c7adb79cc6caabfe2958e82d73d7b80d1468075213)
> * [在`README.md`中执行354行变更](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
> * [删除`README.zh-Hans.md`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-ac136fd5500e4bed851634e02236c48d5d66c90e625abb8e0709bde4d183ad83)
> * [删除`crowdin.yml`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-256aa18d225b85dd7da40aba5091225c2b6c93e8e40f8955fc92be6c5a674afc)
> * [删除`package.json`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
> * [删除`pnpm-lock.yaml`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb)
> * [删除`renovate.json`](https://github.com/sparanoid/chinese-copywriting-guidelines/pull/217/files#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57)
> 
> 上述变更，以我的理解，是 **将[本仓库](https://github.com/sparanoid/chinese-copywriting-guidelines)适配到[Next-DAO团队](https://github.com/Next-DAO)** 的行为。应只存在于[Next-DAO分叉](https://github.com/Next-DAO/chinese-copywriting-guidelines)下，而非提交至本仓库。
> 
> 行动建议：关闭此拉取请求（Close pull request）。

已经关闭了，哥！

**Pull request closed without merging**
